// <auto-generated />
using System;
using Challenge.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Challenge.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Challenge.API.Models.LeadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9371),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9380),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9381),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9381),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9383),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9383),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9384),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9389),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Category = "Home Renovations",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9389),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "angel.hussain@email.com",
                            Name = "Angel Hussain",
                            Phone = "043999999999",
                            Price = 500.5,
                            Status = 0,
                            Suburb = "Yanderra 2574",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9390),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9390),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9391),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 13,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9392),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 14,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9392),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 15,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9393),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 16,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9394),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 17,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9394),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 18,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9395),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 19,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9396),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 20,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9397),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 21,
                            Category = "Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9398),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "silver.bowers@email.com",
                            Name = "Silver Bowers",
                            Phone = "043999999999",
                            Price = 150.0,
                            Status = 1,
                            Suburb = "Carramar 6031",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 22,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9399),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 1,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 23,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9399),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 1,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 24,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9400),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 1,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 25,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9401),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 1,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9402),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 27,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9402),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 28,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9403),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 29,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9404),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 30,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9404),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 31,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9406),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 32,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9407),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 33,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9407),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 34,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9408),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 35,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9409),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 36,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9409),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 37,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9410),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 38,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9411),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 39,
                            Category = "General Building Work",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9411),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "bev.byrne@email.com",
                            Name = "Bev Byrne",
                            Phone = "043999999999",
                            Price = 50.0,
                            Status = 0,
                            Suburb = "Quinns Rocks 6030",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 40,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9412),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 41,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9413),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 42,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9478),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 43,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9479),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 44,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9480),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 45,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9480),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 46,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9481),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 47,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9482),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 48,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9483),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 49,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9483),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        },
                        new
                        {
                            Id = 50,
                            Category = "Interior Painters",
                            CreatedAt = new DateTime(2024, 1, 16, 4, 32, 27, 414, DateTimeKind.Local).AddTicks(9484),
                            Description = "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Email = "reed.robertson@email.com",
                            Name = "Reed Robertson",
                            Phone = "043999999999",
                            Price = 250.09999999999999,
                            Status = 0,
                            Suburb = "Woolooware 2230",
                            TotalPrice = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
